const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;
document.body.insertAdjacentHTML('afterbegin','<div class="scroll-progress" aria-hidden="true"></div>');
requestAnimationFrame(()=>document.body.classList.add('is-ready'));
const menu=document.querySelector('.menu'),links=document.querySelector('.links'),header=document.querySelector('.header'),progress=document.querySelector('.scroll-progress');
if(menu)menu.addEventListener('click',()=>{const open=links.classList.toggle('open');menu.setAttribute('aria-expanded',String(open))});
document.querySelectorAll('.demo-form').forEach(form=>form.addEventListener('submit',e=>{e.preventDefault();const status=form.querySelector('.form-status');status.style.display='block';status.focus();form.reset()}));
const revealTargets=[...document.querySelectorAll('.section-head,.card,.step,.split>*,.trustitem,.panel,.faq details,.band .wrap,.form')];
revealTargets.forEach((el,i)=>{el.classList.add('reveal');if(el.matches('.split>*:first-child'))el.classList.add('from-left');if(el.matches('.split>*:last-child'))el.classList.add('from-right');el.classList.add(`reveal-delay-${i%4}`)});
if(!reduce&&'IntersectionObserver'in window){const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');io.unobserve(e.target)}}),{threshold:.12,rootMargin:'0px 0px -6%'});revealTargets.forEach(el=>io.observe(el))}else revealTargets.forEach(el=>el.classList.add('is-visible'));
let ticking=false;function onScroll(){if(ticking)return;ticking=true;requestAnimationFrame(()=>{const y=scrollY,max=document.documentElement.scrollHeight-innerHeight;progress.style.transform=`scaleX(${max>0?y/max:0})`;header?.classList.toggle('scrolled',y>32);if(!reduce){const media=document.querySelector('.hero-media'),sequence=document.querySelector('.hero-sequence');if(media){const amount=Math.min(y*.11,72);media.style.setProperty('--card-parallax',`${amount*-.35}px`);sequence?.style.setProperty('--parallax-y',`${amount}px`)}}ticking=false})}addEventListener('scroll',onScroll,{passive:true});onScroll();
document.querySelectorAll('a[href]').forEach(a=>a.addEventListener('click',e=>{const u=new URL(a.href,location.href);if(!reduce&&u.origin===location.origin&&u.pathname!==location.pathname&&!a.target){e.preventDefault();document.body.classList.add('is-leaving');setTimeout(()=>location.href=a.href,260)}}));

const hero=document.querySelector('.hero'),heroFrames=[...document.querySelectorAll('.hero-frame')],heroDots=[...document.querySelectorAll('.hero-timeline span')],heroPrev=document.querySelector('.hero-arrow-prev'),heroNext=document.querySelector('.hero-arrow-next');
if(hero&&heroFrames.length){let heroIndex=0,heroTimer;const scheduleHero=()=>{clearTimeout(heroTimer);if(!reduce)heroTimer=setTimeout(()=>showHero(heroIndex+1),7000)};const showHero=index=>{heroFrames[heroIndex]?.classList.remove('is-active');heroFrames[heroIndex]?.tagName==='VIDEO'&&heroFrames[heroIndex].pause();heroDots[heroIndex]?.classList.remove('is-active');heroIndex=(index+heroFrames.length)%heroFrames.length;const frame=heroFrames[heroIndex];frame.classList.add('is-active');heroDots[heroIndex]?.classList.add('is-active');if(frame.tagName==='VIDEO'){frame.currentTime=0;frame.play().catch(()=>{})}scheduleHero()};heroPrev?.addEventListener('click',()=>showHero(heroIndex-1));heroNext?.addEventListener('click',()=>showHero(heroIndex+1));hero.addEventListener('mouseenter',()=>clearTimeout(heroTimer));hero.addEventListener('mouseleave',scheduleHero);hero.addEventListener('focusin',()=>clearTimeout(heroTimer));hero.addEventListener('focusout',e=>{if(!hero.contains(e.relatedTarget))scheduleHero()});document.addEventListener('visibilitychange',()=>document.hidden?clearTimeout(heroTimer):scheduleHero());showHero(0)}
