const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;
document.body.insertAdjacentHTML('afterbegin','<div class="scroll-progress" aria-hidden="true"></div>');
requestAnimationFrame(()=>document.body.classList.add('is-ready'));
const menu=document.querySelector('.menu'),links=document.querySelector('.links'),header=document.querySelector('.header'),progress=document.querySelector('.scroll-progress');
const closeMenu=()=>{if(!menu||!links||!links.classList.contains('open'))return;links.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Open menu')};
if(menu)menu.addEventListener('click',()=>{const open=links.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Close menu':'Open menu')});
document.querySelectorAll('.demo-form').forEach(form=>form.addEventListener('submit',e=>{e.preventDefault();const status=form.querySelector('.form-status');status.style.display='block';status.focus();form.reset()}));
const revealTargets=[...document.querySelectorAll('.section-head,.card,.step,.split>*,.trustitem,.panel,.faq details,.band .wrap,.form')];
revealTargets.forEach((el,i)=>{el.classList.add('reveal');if(el.matches('.split>*:first-child'))el.classList.add('from-left');if(el.matches('.split>*:last-child'))el.classList.add('from-right');el.classList.add(`reveal-delay-${i%4}`)});
if(!reduce&&'IntersectionObserver'in window){const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');io.unobserve(e.target)}}),{threshold:.12,rootMargin:'0px 0px -6%'});revealTargets.forEach(el=>io.observe(el))}else revealTargets.forEach(el=>el.classList.add('is-visible'));
let ticking=false,lastScrollY=scrollY;function onScroll(){if(ticking)return;ticking=true;requestAnimationFrame(()=>{const y=scrollY,max=document.documentElement.scrollHeight-innerHeight;if(y>lastScrollY+2)closeMenu();progress.style.transform=`scaleX(${max>0?y/max:0})`;header?.classList.toggle('scrolled',y>32);if(!reduce){const media=document.querySelector('.hero-media'),sequence=document.querySelector('.hero-sequence');if(media){const amount=Math.min(y*.11,72);media.style.setProperty('--card-parallax',`${amount*-.35}px`);sequence?.style.setProperty('--parallax-y',`${amount}px`)}}lastScrollY=y;ticking=false})}addEventListener('scroll',onScroll,{passive:true});onScroll();
document.addEventListener('keydown',event=>{if(event.key==='Escape')closeMenu()});
document.querySelectorAll('.faq details').forEach(detail=>{const summary=detail.querySelector('summary'),answer=detail.querySelector('p');if(!summary||reduce||typeof detail.animate!=='function')return;let animation=null;summary.addEventListener('click',event=>{event.preventDefault();if(animation)animation.finish();const opening=!detail.open;const start=detail.offsetHeight;if(opening)detail.open=true;const styles=getComputedStyle(detail),closedHeight=summary.offsetHeight+parseFloat(styles.paddingTop)+parseFloat(styles.paddingBottom),end=opening?detail.scrollHeight:closedHeight;detail.style.overflow='hidden';animation=detail.animate([{height:`${start}px`},{height:`${end}px`}],{duration:420,easing:'cubic-bezier(.22,1,.36,1)'});if(answer)answer.animate(opening?[{opacity:0,transform:'translateY(-8px)'},{opacity:1,transform:'none'}]:[{opacity:1,transform:'none'},{opacity:0,transform:'translateY(-6px)'}],{duration:opening?360:220,easing:'ease-out'});animation.onfinish=()=>{if(!opening)detail.open=false;detail.style.height='';detail.style.overflow='';animation=null};animation.oncancel=()=>{detail.style.height='';detail.style.overflow='';animation=null}})});
document.querySelectorAll('a[href]').forEach(a=>a.addEventListener('click',e=>{const u=new URL(a.href,location.href);if(!reduce&&u.origin===location.origin&&u.pathname!==location.pathname&&!a.target){e.preventDefault();document.body.classList.add('is-leaving');setTimeout(()=>location.href=a.href,260)}}));

const hero=document.querySelector('.hero'),heroFrames=[...document.querySelectorAll('.hero-frame')],heroDots=[...document.querySelectorAll('.hero-timeline span')],heroPrev=document.querySelector('.hero-arrow-prev'),heroNext=document.querySelector('.hero-arrow-next');
if(hero&&heroFrames.length){let heroIndex=0,heroTimer;const scheduleHero=()=>{clearTimeout(heroTimer);if(!reduce)heroTimer=setTimeout(()=>showHero(heroIndex+1),7000)};const showHero=index=>{heroFrames[heroIndex]?.classList.remove('is-active');heroFrames[heroIndex]?.tagName==='VIDEO'&&heroFrames[heroIndex].pause();heroDots[heroIndex]?.classList.remove('is-active');heroIndex=(index+heroFrames.length)%heroFrames.length;const frame=heroFrames[heroIndex];frame.classList.add('is-active');heroDots[heroIndex]?.classList.add('is-active');if(frame.tagName==='VIDEO'){frame.currentTime=0;frame.play().catch(()=>{})}scheduleHero()};heroPrev?.addEventListener('click',()=>showHero(heroIndex-1));heroNext?.addEventListener('click',()=>showHero(heroIndex+1));hero.addEventListener('mouseenter',()=>clearTimeout(heroTimer));hero.addEventListener('mouseleave',scheduleHero);hero.addEventListener('focusin',()=>clearTimeout(heroTimer));hero.addEventListener('focusout',e=>{if(!hero.contains(e.relatedTarget))scheduleHero()});document.addEventListener('visibilitychange',()=>document.hidden?clearTimeout(heroTimer):scheduleHero());showHero(0)}
